# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rewrich/Downloads/Beeftext

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rewrich/Downloads/Beeftext

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rewrich/Downloads/Beeftext/CMakeFiles /home/rewrich/Downloads/Beeftext//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rewrich/Downloads/Beeftext/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XMiLib

# Build rule for target.
XMiLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XMiLib
.PHONY : XMiLib

# fast build rule for target.
XMiLib/fast:
	$(MAKE) $(MAKESILENT) -f Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib.dir/build.make Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib.dir/build
.PHONY : XMiLib/fast

#=============================================================================
# Target rules for targets named XMiLib_autogen_timestamp_deps

# Build rule for target.
XMiLib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XMiLib_autogen_timestamp_deps
.PHONY : XMiLib_autogen_timestamp_deps

# fast build rule for target.
XMiLib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib_autogen_timestamp_deps.dir/build.make Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib_autogen_timestamp_deps.dir/build
.PHONY : XMiLib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named XMiLib_autogen

# Build rule for target.
XMiLib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XMiLib_autogen
.PHONY : XMiLib_autogen

# fast build rule for target.
XMiLib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib_autogen.dir/build.make Submodules/XMiLib/XMiLib/CMakeFiles/XMiLib_autogen.dir/build
.PHONY : XMiLib_autogen/fast

#=============================================================================
# Target rules for targets named translations

# Build rule for target.
translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 translations
.PHONY : translations

# fast build rule for target.
translations/fast:
	$(MAKE) $(MAKESILENT) -f Beeftext/CMakeFiles/translations.dir/build.make Beeftext/CMakeFiles/translations.dir/build
.PHONY : translations/fast

#=============================================================================
# Target rules for targets named Beeftext

# Build rule for target.
Beeftext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Beeftext
.PHONY : Beeftext

# fast build rule for target.
Beeftext/fast:
	$(MAKE) $(MAKESILENT) -f Beeftext/CMakeFiles/Beeftext.dir/build.make Beeftext/CMakeFiles/Beeftext.dir/build
.PHONY : Beeftext/fast

#=============================================================================
# Target rules for targets named Beeftext_autogen_timestamp_deps

# Build rule for target.
Beeftext_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Beeftext_autogen_timestamp_deps
.PHONY : Beeftext_autogen_timestamp_deps

# fast build rule for target.
Beeftext_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Beeftext/CMakeFiles/Beeftext_autogen_timestamp_deps.dir/build.make Beeftext/CMakeFiles/Beeftext_autogen_timestamp_deps.dir/build
.PHONY : Beeftext_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Beeftext_autogen

# Build rule for target.
Beeftext_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Beeftext_autogen
.PHONY : Beeftext_autogen

# fast build rule for target.
Beeftext_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Beeftext/CMakeFiles/Beeftext_autogen.dir/build.make Beeftext/CMakeFiles/Beeftext_autogen.dir/build
.PHONY : Beeftext_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Beeftext_autogen"
	@echo "... Beeftext_autogen_timestamp_deps"
	@echo "... XMiLib_autogen"
	@echo "... XMiLib_autogen_timestamp_deps"
	@echo "... translations"
	@echo "... Beeftext"
	@echo "... XMiLib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

